/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicolombo.pb.Gastos.vistas;
import co.edu.unicolombo.pb.Gastos.Producto;
import co.edu.unicolombo.pb.persistencia.AlmacenamientoP;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class VentanaProducto1 extends javax.swing.JFrame {

    /**
     * Creates new form VentanaProducto
     */
    public VentanaProducto1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        ButtonGuardarP = new javax.swing.JButton();
        ButtonBuscarP = new javax.swing.JButton();
        ButtonEditarP = new javax.swing.JButton();
        ButtonEliminarP = new javax.swing.JButton();
        ButtonCancelarP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("FORMULARIO  GESTION DE PRODUCTO");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/pb/Gastos/vistas/iconos/dairy-products_1.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)), "Datos de produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Codigo");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText(" Valor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecio)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ButtonGuardarP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ButtonGuardarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/pb/Gastos/vistas/iconos/Guardar48px.png"))); // NOI18N
        ButtonGuardarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGuardarPActionPerformed(evt);
            }
        });

        ButtonBuscarP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ButtonBuscarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/pb/Gastos/vistas/iconos/Search48px.png"))); // NOI18N
        ButtonBuscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarPActionPerformed(evt);
            }
        });

        ButtonEditarP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ButtonEditarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/pb/Gastos/vistas/iconos/Editar24px.png"))); // NOI18N
        ButtonEditarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarPActionPerformed(evt);
            }
        });

        ButtonEliminarP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ButtonEliminarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/pb/Gastos/vistas/iconos/Eliminar24px.png"))); // NOI18N
        ButtonEliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarPActionPerformed(evt);
            }
        });

        ButtonCancelarP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ButtonCancelarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/pb/Gastos/vistas/iconos/Cancelar48px.png"))); // NOI18N
        ButtonCancelarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButtonCancelarP)
                .addGap(53, 53, 53)
                .addComponent(ButtonEliminarP)
                .addGap(42, 42, 42)
                .addComponent(ButtonEditarP)
                .addGap(38, 38, 38)
                .addComponent(ButtonBuscarP)
                .addGap(60, 60, 60)
                .addComponent(ButtonGuardarP)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonGuardarP)
                    .addComponent(ButtonBuscarP)
                    .addComponent(ButtonEditarP)
                    .addComponent(ButtonEliminarP)
                    .addComponent(ButtonCancelarP))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonGuardarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGuardarPActionPerformed
       String codigo = txtCodigo.getText();
    String nombre = txtName.getText();
    String precioText = txtPrecio.getText();

    boolean isNumber = true;
    double precio = 0.0;

    if (!precioText.isEmpty()) {
        try {
            precio = Double.parseDouble(precioText);
        } catch (NumberFormatException e) {
            isNumber = false;
        }
    } else {
        isNumber = false;
    }

    if (!isNumber) {
        JOptionPane.showMessageDialog(this, "Error: ingresa un número válido para el precio");
    } else {
        if (Producto.ProductosBD.containsKey(codigo)) {
            JOptionPane.showMessageDialog(this, "El producto con código: " + codigo + " ya está registrado");
        } else {
            Producto prod = new Producto();
            prod.id = codigo;
            prod.nombre = nombre;
            prod.valor = precio;

            Producto.ProductosBD.put(codigo, prod);

            int total = Producto.ProductosBD.size();

            try {
                AlmacenamientoP.guardar(Producto.ProductosBD);
                JOptionPane.showMessageDialog(this, "Producto registrado con éxito!!\nTotal: " + total);
                LimpiarCampos();
            } catch (IOException error) {
                JOptionPane.showMessageDialog(this, error.getMessage());
            }
        }
    }
    }//GEN-LAST:event_ButtonGuardarPActionPerformed

    private void ButtonBuscarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarPActionPerformed
         String codigoBuscar = txtCodigo.getText(); // Obtener el código a buscar desde el campo de texto
    
    if (Producto.ProductosBD.containsKey(codigoBuscar)) {
        Producto productoEncontrado = Producto.ProductosBD.get(codigoBuscar);
        // Mostrar información del producto encontrado en los campos correspondientes (por ejemplo, txtName y txtPrecio)
        txtName.setText(productoEncontrado.nombre);
        txtPrecio.setText(String.valueOf(productoEncontrado.valor));
        JOptionPane.showMessageDialog(this, "Producto encontrado:\nCódigo: " + productoEncontrado.id + "\nNombre: " + productoEncontrado.nombre + "\nPrecio: " + productoEncontrado.valor);
    } else {
        JOptionPane.showMessageDialog(this, "No se encontró ningún producto con el código: " + codigoBuscar);
    }

    }//GEN-LAST:event_ButtonBuscarPActionPerformed

    private void ButtonEditarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarPActionPerformed
 String codigo = txtCodigo.getText();
String nombre = txtName.getText();
String precioTexto = txtPrecio.getText();

if (Producto.ProductosBD.containsKey(codigo)) {
    Producto productoExistente = Producto.ProductosBD.get(codigo);
    productoExistente.nombre = nombre;
    productoExistente.valor = Double.parseDouble(precioTexto);

    Producto.ProductosBD.put(codigo, productoExistente);

    try {
        AlmacenamientoP.guardar(Producto.ProductosBD);
        JOptionPane.showMessageDialog(this, "Producto editado con éxito");
        LimpiarCampos();
    } catch (IOException error) {
        JOptionPane.showMessageDialog(this, "Error al editar el producto: " + error.getMessage());
    }
} else {
    JOptionPane.showMessageDialog(this, "El producto con código " + codigo + " no existe. No se puede editar.");
}

    }//GEN-LAST:event_ButtonEditarPActionPerformed

    private void ButtonEliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarPActionPerformed
 String codigo = txtCodigo.getText();

    try {
        if (Producto.ProductosBD.containsKey(codigo)) {
            Producto.ProductosBD.remove(codigo);

            int total = Producto.ProductosBD.size();

            AlmacenamientoP.guardar(Producto.ProductosBD);
            JOptionPane.showMessageDialog(this, "Producto eliminado con éxito\nTotal: " + total);
            LimpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Este producto con codigo " + codigo + " no existe. No se puede eliminar.");
        }
    } catch (IOException error) {
        JOptionPane.showMessageDialog(this, "Error al guardar los cambios tras la eliminación del producto: " + error.getMessage());
    }

    }//GEN-LAST:event_ButtonEliminarPActionPerformed

    private void ButtonCancelarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarPActionPerformed
               int opcion = JOptionPane.showConfirmDialog(this, " Desea cerrar el formulario? ",
                "ALERTA - CONFIRMAR ", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opcion == JOptionPane.YES_OPTION) {
            this.dispose();
        }

    }//GEN-LAST:event_ButtonCancelarPActionPerformed
public void LimpiarCampos(){
        txtCodigo.setText("");
        txtName.setText("");
        txtPrecio.setText("");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaProducto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaProducto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaProducto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaProducto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaProducto1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuscarP;
    private javax.swing.JButton ButtonCancelarP;
    private javax.swing.JButton ButtonEditarP;
    private javax.swing.JButton ButtonEliminarP;
    private javax.swing.JButton ButtonGuardarP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
